#------------------------------------------------------------------------------
# Returns the current timestamp as a string.

name: neon-timestamp
description: Returns the current timestamp as a string.
outputs:
  timestamp:
    description: Returns as the current time formatted as: YYYY-MM-DD HH-MM:SSZ
runs:
  using: composite
  steps:
  - name: get-time
    shell: pwsh
    run: |
      $utcNow = [System.DateTime]::UtcNow
      Write-Output "::set-output name=reboot-required::" + $utcNow.ToString("u")
      
